---
exp_arguments:
  n_classes: 2
  save_exp_code: TCGA_NSCLC_UNI_100
  raw_save_dir: D:/ADGA-main/heatmaps/heatmap_raw_results_NSCLC_UNI
  production_save_dir: D:/ADGA-main/heatmaps/heatmap_production_results_NSCLC_UNI
  batch_size: 1

data_arguments:
  data_dir: D:/ADGA_Datasets/heatmap_slides/NSCLC/LUAD/Slides
  patch_dir: D:/ADGA_Datasets/heatmap_slides/NSCLC/LUAD/patches
  feat_dir: D:/ADGA_Datasets/NSCLC/feats-UNI-reduced-graph/pt_files
  process_list: D:/ADGA-main/dataset_csv/tcga_nsclc_heatmap_LUAD.csv
  preset: null
  slide_ext: .svs
  label_dict:
    LUAD: 0
    LUSC: 1

patching_arguments:
  patch_size: 256
  overlap: 0.0
  patch_level: 0
  custom_downsample: 1

model_arguments:
  ckpt_path: D:/ADGA-main/results/TCGA_NSCLC_UNI_100_s1/s_0_best_checkpoint.pt
  model_type: clam_sb
  initiate_fn: initiate_model
  model_size: small
  drop_out: 0.25
  embed_dim: 1024

heatmap_arguments:
  vis_level: -1
  alpha: 0.4
  blank_canvas: false
  save_orig: true
  save_ext: jpg
  use_ref_scores: false
  blur: false
  use_center_shift: false
  use_roi: false
  calc_heatmap: false
  binarize: false
  binary_thresh: -1
  custom_downsample: 1
  cmap: jet
  convert_to_percentiles: true

sample_arguments:
  samples:
    - name: topk_high_attention_nsclc_uni
      sample: true
      seed: 1
      k: 15
      mode: topk

data_loader_arguments:
  num_workers: 0

# LUSC
# data_dir: D:/ADGA_Datasets/heatmap_slides/NSCLC/LUSC/Slides
# patch_dir: D:/ADGA_Datasets/heatmap_slides/NSCLC/LUSC/patches
# process_list: D:/ADGA-main/dataset_csv/tcga_nsclc_heatmap_LUSC.csv

# CHIEF脚本修改
# save_exp_code: TCGA_NSCLC_CHIEF_100
# raw_save_dir: D:/ADGA-main/heatmaps/heatmap_raw_results_NSCLC_CHIEF
# production_save_dir: D:/ADGA-main/heatmaps/heatmap_production_results_NSCLC_CHIEF
# feat_dir: D:/ADGA_Datasets/NSCLC/feats-CHIEF-reduced-graph/pt_files
# ckpt_path: D:/ADGA-main/results/TCGA_NSCLC_CHIEF_100_s1/s_0_best_checkpoint.pt
# embed_dim: 768
